In [7]:
#creating arrays
from numpy import *
arr2=array([1,2,3])
print(arr2)


[1 2 3]


In [10]:
def func3(a,b):
    print("The sum is", a+b)
func3(5,7)

The sum is 12


In [1]:
text="234patwariparavivekanandasaranigarfa700078"
print([x for x in text if x.isdigit()])

['2', '3', '4', '7', '0', '0', '0', '7', '8']


In [4]:
#docstring in function
def func1(a,b):
    """This is a function stating docstring"""
    av=(a+b)/2
    return av
func1(5,9)
print(func1.__doc__)

This is a function stating docstring


In [3]:
from numpy import *
arrz=linspace(1,15,15) #16 divides it in equal parts
print(arrz)
arrz1=linspace(1,15)
print(arrz1)#not specifying divides it into equal parts

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
[ 1.          1.28571429  1.57142857  1.85714286  2.14285714  2.42857143
  2.71428571  3.          3.28571429  3.57142857  3.85714286  4.14285714
  4.42857143  4.71428571  5.          5.28571429  5.57142857  5.85714286
  6.14285714  6.42857143  6.71428571  7.          7.28571429  7.57142857
  7.85714286  8.14285714  8.42857143  8.71428571  9.          9.28571429
  9.57142857  9.85714286 10.14285714 10.42857143 10.71428571 11.
 11.28571429 11.57142857 11.85714286 12.14285714 12.42857143 12.71428571
 13.         13.28571429 13.57142857 13.85714286 14.14285714 14.42857143
 14.71428571 15.        ]


In [8]:
from numpy import *
arr1=array([1,2,3,4,5])
print(arr1+5)
    
    

[ 6  7  8  9 10]


In [24]:

def calc1():
    int1=int(input("Enter a variable of your choice \n"))
    for i in range(2,int1):
        if int1%i==0:
            print("The number is not prime")
            break
    else:
        v3=sqrt(int1)
        print("Prime number square root",v3)
        again2()
def again2():
    print("Do you want to continue with program?: \n"+"y for yes \n"+"n for no \n")
    callback=input("Enter your choice \n")
    if callback=='y':
        calc1()
    elif callback=='n':
        print("Okay Tata")
    else:
        again2()
        
calc1()


Enter a variable of your choice 
23
Prime number square root 4.795831523312719
Do you want to continue with program?: 
y for yes 
n for no 

Enter your choice 
n
Okay Tata


In [5]:
j=3
c=0
while(True):
    print("*"*j)
    c+=1
    if c==3:
        break

***
***
***


In [7]:
from numpy import *
arrzz=([1,2,44,36])
print(sort(arrzz))
#creating a new copying array
arrzz1=arrzz.copy()#this is a deep copy, wont change values depending on others
print(arrzz1)

[ 1  2 36 44]
[1, 2, 44, 36]


In [10]:
#exception handling
i1=input("Enter a variable")
i2=input("Enter a variable")
try:
    print(int(i1)+int(i2))

except Exception as e:
    print(e)

print("This is an important line")

Enter a variableww
Enter a variable23
invalid literal for int() with base 10: 'ww'
This is an important line


In [6]:
#array
from numpy import *
vv=array([
    [2,3,5],
    [4,5,6]
    ])
print(vv)
print(vv.dtype)
print(vv.ndim)#gives you the number of arrays
print(vv.shape)

[[2 3 5]
 [4 5 6]]
int32
2
(2, 3)


In [7]:
vv2=vv.flatten()
print(vv2)

[2 3 5 4 5 6]


In [10]:
vv3=array([
    [2,8,9,6,5,4],
    [4,5,6,7,2,1]
])
vv4=vv3.reshape(2,2,3)
print(vv4)

[[[2 8 9]
  [6 5 4]]

 [[4 5 6]
  [7 2 1]]]


In [14]:
vv5=array([
    [2,4,5],
    [6,7,8]
])
vv5i=vv5.reshape(3,2)
print(vv5i)

[[2 4]
 [5 6]
 [7 8]]


In [3]:
#creating matrix
from numpy import *
m=matrix('1 2 3; 4 3 4; 6 8 9')#semicolon separates the rows and columns in this case 3*3 column
m1=matrix('2,3,5 ; 4,5,6; 4,6,7')
m3=m*m1
print(m)
print(diagonal(m)) #gives just diagonal values
print(m3)

[[1 2 3]
 [4 3 4]
 [6 8 9]]
[1 3 9]
[[ 22  31  38]
 [ 36  51  66]
 [ 80 112 141]]


In [31]:
#fibonacci 
n1=int(input("Enter your number"))
x=0
y=1
z=0
while(z<=n1):
    print(z,end=" ")
    x=y
    y=z
    z=x+y

    

Enter your number15
0 1 1 2 3 5 8 13 

In [19]:
l=[12,23,45,66,80,98,24,45,32,31,99]
#count the number of even/odd passing a list through a function
def c1(l):
    e=0
    o=0
    for i in l:
        if i%2==0:
            e+=1
        else:
            o+=1
    return e,o

e,o=c1(l)


print(e)
print(o)

print("Even number :{} and odd number:{}".format(e,o))

6
5
Even number :6 and odd number:5


In [16]:
#factorial iterative approach

def factorial1(n):
    fac=1
    for i in range(n):
        fac=fac*(i+1)
    return fac

factorial1(n)

n=int(input("Enter a number \t"))
print(factorial1(n))

Enter a number 	5
120


In [14]:
n=int(input())
sum1=0
for i in range(1,n):
    if n%(i)==0:
        sum1+=i
if sum1==n:
    print("Perfect number")
else:
    print("not perfect number")

4
not perfect number


In [20]:
import calendar
print(calendar.month(1998,9))

   September 1998
Mo Tu We Th Fr Sa Su
    1  2  3  4  5  6
 7  8  9 10 11 12 13
14 15 16 17 18 19 20
21 22 23 24 25 26 27
28 29 30



In [22]:
print(calendar.calendar(2000,c=3,m=3))

                               2000

      January                February                March
Mo Tu We Th Fr Sa Su   Mo Tu We Th Fr Sa Su   Mo Tu We Th Fr Sa Su
                1  2       1  2  3  4  5  6          1  2  3  4  5
 3  4  5  6  7  8  9    7  8  9 10 11 12 13    6  7  8  9 10 11 12
10 11 12 13 14 15 16   14 15 16 17 18 19 20   13 14 15 16 17 18 19
17 18 19 20 21 22 23   21 22 23 24 25 26 27   20 21 22 23 24 25 26
24 25 26 27 28 29 30   28 29                  27 28 29 30 31
31

       April                   May                    June
Mo Tu We Th Fr Sa Su   Mo Tu We Th Fr Sa Su   Mo Tu We Th Fr Sa Su
                1  2    1  2  3  4  5  6  7             1  2  3  4
 3  4  5  6  7  8  9    8  9 10 11 12 13 14    5  6  7  8  9 10 11
10 11 12 13 14 15 16   15 16 17 18 19 20 21   12 13 14 15 16 17 18
17 18 19 20 21 22 23   22 23 24 25 26 27 28   19 20 21 22 23 24 25
24 25 26 27 28 29 30   29 30 31               26 27 28 29 30

        July                  August            

In [24]:
calendar.weekday(2021,6,16)
calendar.isleap(2022)

False

In [40]:
def pyramid(rows):
    for i in range(rows):
        print(' '*(rows-i-1)+"*"*(2*i+1))
    for j in range(rows-1,0,-1):
        print(" "*(rows-j)+"*"*(2*j-1))

pyramid(10)

         *
        ***
       *****
      *******
     *********
    ***********
   *************
  ***************
 *****************
*******************
 *****************
  ***************
   *************
    ***********
     *********
      *******
       *****
        ***
         *
